name: ci
on: push

jobs:
  run:
    runs-on: ubuntu-22.04

    timeout-minutes: 10

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - name: check system
        run: |
          lscpu
          free -h
          df -h 
          cat /etc/os-release

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: run
        run: |
          which conda 
          conda init bash
          conda activate base
          bash test.sh
